### ISSUE TITLE
Relationship between 'threshold' value and 'promotion_throughput' value in autonuma balancing

### ISSUE THREAD

**Issue by JunyeolYu** [EMDC-OS/CXL-AutoNUMA#7]
Hello, I am enjoying the patch contents with interest.

Looking at the patch details, it seems that the th(threshold) value is directly adjusted in autonuma balancing, and a new 'promotion_throughput' value is created and used.
I am curious whether there is a relationship between the two variables, and if so, what kind of relationship it has.

Thank you.

**Comment by nicedavid98** [comment]
Hello, thank you for your interest.

1. The current Linux kernel's autonuma memory tiering mode uses 'access time - scan time' as a metric to determine hot pages. That is, the smaller the value, the hotter the page is assumed to be.

2. When 'access time - scan time' is below the 'th' value, the kernel considers the page to be hot and promotes it to higher tier memory.

3. The value 'promotion_throughput' is an auxiliary indicator used to appropriately adjust this 'th' value. Instead of changing the 'th' value directly, we dynamically change the 'th' value according to the page promotion speed set by the user.

Thank you!
